const $=id=>document.getElementById(id),pause=()=>new Promise(r=>setTimeout(r,0));
let groups=new Map(),modelFiles=[],scanId=0,scanning=false;
function status(s,error=false){$('status').textContent=s;$('status').classList.toggle('error',error)}
function ready(){$('load').disabled=!( !scanning && groups.has($('series').value)&&(modelFiles.length||(window.importedPresets||[]).length))}
function numbers(d,tag){return (d.string(tag)||'').split('\\').filter(Boolean).map(Number)}
function parse(bytes){return dicomParser.parseDicom(bytes,{untilTag:'x7fe00010'})}
function header(d,file){const h={file,uid:d.string('x0020000e'),sop:d.string('x00080018'),name:d.string('x0008103e')||'未命名序列',modality:d.string('x00080060')||'',rows:d.uint16('x00280010'),cols:d.uint16('x00280011'),orientation:numbers(d,'x00200037'),position:numbers(d,'x00200032'),spacing:numbers(d,'x00280030'),frames:Number(d.string('x00280008')||1),frame:d.string('x00200052'),syntax:d.string('x00020010')||'1.2.840.10008.1.2'};if(!h.uid||!h.rows||!h.cols||!d.elements.x7fe00010)return null;return h}
$('dicom').onchange=async e=>{scanning=true;const token=++scanId,files=Array.from(e.target.files);groups=new Map();$('series').replaceChildren();ready();let skipped=0;status('扫描 DICOM 文件夹…');
for(let i=0;i<files.length;i++){if(token!==scanId)return;const f=files[i];try{const bytes=new Uint8Array(await f.arrayBuffer());if(token!==scanId)return;const d=parse(bytes),h=header(d,f);if(h){if(!groups.has(h.uid))groups.set(h.uid,[]);groups.get(h.uid).push(h)}else skipped++}catch{skipped++}if(i%20===0){status(`扫描 ${i+1} / ${files.length} 个文件…`);await pause()}}
if(token!==scanId)return;const sorted=[...groups].sort((a,b)=>b[1].length-a[1].length);for(const[uid,hs]of sorted){const h=hs[0],o=document.createElement('option');o.value=uid;o.textContent=`${h.modality} · ${h.name} · ${hs.length} 层 · ${h.cols}×${h.rows} · ${h.file.webkitRelativePath.split('/').slice(0,-1).join('/')}`;$('series').append(o)}$('dicomInfo').textContent=`${groups.size} 个序列，${files.length-skipped} 个影像文件`;
scanning=false;status(groups.size?`请选择与模型对应的影像序列。${skipped?'跳过 '+skipped+' 个非影像或无法识别的文件。':''}`:'未找到可读取的 DICOM 影像文件。',!groups.size);ready()};
$('models').onchange=e=>{modelFiles=Array.from(e.target.files).filter(f=>/\.stl$/i.test(f.name)).sort((a,b)=>a.name.localeCompare(b.name));$('modelInfo').textContent=`${modelFiles.length} 个 STL · ${(modelFiles.reduce((s,f)=>s+f.size,0)/1048576).toFixed(1)} MiB`;status(modelFiles.length?'模型已选择；确认序列后点击「加载查看」。':'文件夹中没有 STL，请选择包含 STL 子文件夹的目录。',!modelFiles.length);ready()};
$('series').onchange=ready;$('change').onclick=()=>{$('picker').hidden=false;$('change').hidden=true;$('frame').style.height='calc(100vh - 360px)'};
function fail(message){throw Error(message)}
function close(a,b,tol=1e-4){return a.length===b.length&&a.every((v,i)=>Number.isFinite(v)&&Math.abs(v-b[i])<tol)}
async function readVolume(headers){
const hs=[...headers],h=hs[0];if(hs.length<2)fail('该序列不足两层，无法重建三视图。');
if(!close(h.orientation,[1,0,0,0,1,0]))fail('此版支持标准轴位 DICOM（方向 1,0,0,0,1,0）。所选序列为斜位或其他方向，请选择胸部 Body 0.5 序列。');
if(h.position.length!==3||h.spacing.length!==2||h.spacing.some(v=>!Number.isFinite(v)||v<=0))fail('DICOM 缺少有效的空间位置或像素间距。');
const uids=new Set();for(const t of hs){if(t.sop&&uids.has(t.sop))fail('序列含重复 DICOM 实例，请去除重复副本后重试。');uids.add(t.sop);if(t.frames!==1)fail('暂不支持增强型多帧 DICOM。');if(t.rows!==h.rows||t.cols!==h.cols||!close(t.orientation,h.orientation)||!close(t.spacing,h.spacing)||t.frame!==h.frame)fail('序列中存在不一致的尺寸、方向或坐标参考。');if(t.position.length!==3||!close(t.position.slice(0,2),h.position.slice(0,2),.01))fail('序列存在倾斜或平面位移，不能按标准轴位直接重建。')}
hs.sort((a,b)=>a.position[2]-b.position[2]);const dz=(hs.at(-1).position[2]-hs[0].position[2])/(hs.length-1);if(!Number.isFinite(dz)||dz<=0)fail('切片位置重复或无效。');for(let k=1;k<hs.length;k++)if(Math.abs(hs[k].position[2]-hs[k-1].position[2]-dz)>Math.max(.01,dz*.01))fail('切片间距不均匀或有缺层，请使用完整的等间距序列。');
const n=h.cols*h.rows*hs.length;if(n>350000000)fail('序列过大，超过此查看器的内存上限。');const ct=new Float32Array(n);let modality=h.modality;
for(let k=0;k<hs.length;k++){const bytes=new Uint8Array(await hs[k].file.arrayBuffer()),d=parse(bytes),syntax=d.string('x00020010')||'1.2.840.10008.1.2';if(!['1.2.840.10008.1.2','1.2.840.10008.1.2.1','1.2.840.10008.1.2.2'].includes(syntax))fail('该序列使用压缩像素编码；此离线版仅支持未压缩 DICOM，请先在 Slicer 导出为未压缩 DICOM。');const bits=d.uint16('x00280100'),stored=d.uint16('x00280101'),high=d.uint16('x00280102'),signed=d.uint16('x00280103'),photo=(d.string('x00280004')||'').trim();if(![8,16].includes(bits)||!(stored>0&&stored<=bits)||high<stored-1||high>=bits||d.uint16('x00280002')!==1||photo!=='MONOCHROME2')fail('仅支持 MONOCHROME2 的 8/16 位单通道 DICOM。');
const slope=Number(d.string('x00281053')||1),intercept=Number(d.string('x00281052')||0);if(!Number.isFinite(slope)||!Number.isFinite(intercept))fail('无效的像素灰度转换参数。');const el=d.elements.x7fe00010,count=h.cols*h.rows;if(el.encapsulatedPixelData||el.length<count*bits/8)fail('像素数据不完整或需要解码。');const view=new DataView(bytes.buffer,bytes.byteOffset+el.dataOffset,count*bits/8),le=syntax!=='1.2.840.10008.1.2.2',mask=(1<<stored)-1,sign=1<<(stored-1),shift=high-stored+1;
for(let i=0;i<count;i++){let v=((bits===16?view.getUint16(i*2,le):view.getUint8(i))>>>shift)&mask;if(signed&&v&sign)v-=1<<stored;ct[k*count+i]=v*slope+intercept}if(k%8===0){status(`读取 DICOM 像素 ${k+1} / ${hs.length}…`);await pause()}}
const origin=hs[0].position,[sy,sx]=h.spacing,centerRAS=[-(origin[0]+(h.cols-1)*sx/2),-(origin[1]+(h.rows-1)*sy/2),origin[2]+(hs.length-1)*dz/2];return {ct,meta:{dims:[h.cols,h.rows,hs.length],spacing:[sx,sy,dz],originLPS:origin,centerRAS,description:h.name,modality}};
}
function color(name){if(/lung/.test(name))return [0.48,.7,.87];if(/rib|vertebra|humerus|scapula|clavicula|sternum|costal/.test(name))return [.91,.84,.64];if(/vein|vena/.test(name))return [.36,.54,.85];if(/aorta|artery|trunk/.test(name))return [.88,.27,.26];if(/heart|atrial/.test(name))return [.82,.43,.45];if(/trachea/.test(name))return [.35,.83,.75];if(/liver/.test(name))return [.68,.39,.25];return [.73,.58,.76]}
function readSTL(buffer,name,center,ras){const dv=new DataView(buffer),count=buffer.byteLength>=84?dv.getUint32(80,true):0;let positions,normals;
if(count&&84+count*50===buffer.byteLength){positions=new Float32Array(count*9);for(let f=0;f<count;f++){const offset=84+f*50;for(let j=0;j<9;j++)positions[f*9+j]=dv.getFloat32(offset+12+j*4,true)}}else{const txt=new TextDecoder().decode(buffer),matches=txt.matchAll(/\bvertex\s+([-+\d.eE]+)\s+([-+\d.eE]+)\s+([-+\d.eE]+)/g),arr=[];for(const m of matches)arr.push(+m[1],+m[2],+m[3]);if(!arr.length||arr.length%9)fail(name+' 不是有效的二进制或 ASCII STL。');positions=new Float32Array(arr)}
for(let i=0;i<positions.length;i+=3){const x=positions[i],y=positions[i+1],z=positions[i+2];if(![x,y,z].every(Number.isFinite))fail(name+' 含无效顶点。');positions[i]=((ras?x:-x)-center[0])/1000;positions[i+1]=(z-center[2])/1000;positions[i+2]=-((ras?y:-y)-center[1])/1000}
// STL has separate vertices per triangle. Flat normals preserve the input surface without extra indexing.
normals=new Float32Array(positions.length);for(let i=0;i<positions.length;i+=9){const ax=positions[i+3]-positions[i],ay=positions[i+4]-positions[i+1],az=positions[i+5]-positions[i+2],bx=positions[i+6]-positions[i],by=positions[i+7]-positions[i+1],bz=positions[i+8]-positions[i+2];let x=ay*bz-az*by,y=az*bx-ax*bz,z=ax*by-ay*bx,l=Math.hypot(x,y,z)||1;for(let j=0;j<9;j+=3){normals[i+j]=x/l;normals[i+j+1]=y/l;normals[i+j+2]=z/l}}
return {name,positions,normals,color:color(name)};
}
$('load').onclick=async()=>{const selected=groups.get($('series').value),files=[...modelFiles],ras=$('coord').value==='RAS';if(!selected)return;const controls=[$('load'),$('dicom'),$('models'),$('series'),$('coord')];controls.forEach(e=>e.disabled=true);$('frame').src='about:blank';$('frame').removeAttribute('srcdoc');window.currentData=null;status('检查 DICOM 空间信息…');try{const data=await readVolume(selected);data.modelData=[];for(let i=0;i<files.length;i++){status(`读取模型 ${i+1} / ${files.length} · ${files[i].name}`);await pause();data.modelData.push(readSTL(await files[i].arrayBuffer(),files[i].name.replace(/\.stl$/i,''),data.meta.centerRAS,ras))}data.meta.models=files.length;
let overlap=false;const [nx,ny,nz]=data.meta.dims,[sx,sy,sz]=data.meta.spacing,half=[(nx-1)*sx/2000,(nz-1)*sz/2000,(ny-1)*sy/2000];for(const m of data.modelData){const min=[Infinity,Infinity,Infinity],max=[-Infinity,-Infinity,-Infinity];for(let i=0;i<m.positions.length;i+=3)for(let a=0;a<3;a++){min[a]=Math.min(min[a],m.positions[i+a]);max[a]=Math.max(max[a],m.positions[i+a])}if(min.every((v,a)=>v<=half[a]&&max[a]>=-half[a]))overlap=true}if(files.length&&!overlap)fail('模型与影像没有空间交叠，请确认同一病例、毫米单位及 LPS/RAS 坐标选择。');
window.currentData=data;$('frame').srcdoc=VIEWER_HTML;$('frame').style.height='calc(100vh - 48px)';$('picker').hidden=true;$('change').hidden=false;status(`${data.meta.description} · ${data.meta.dims[2]} 层 · ${files.length} 个 STL · 正在绘制…`);
}catch(e){window.currentData=null;status('加载失败：'+(e.message||e),true);$('picker').hidden=false}finally{controls.forEach(e=>e.disabled=false);ready()}};
window.viewerLoaded=()=>{status('已从所选文件夹加载 · 本地离线');window.currentData=null};
window.viewerFailed=message=>{status('显示失败：'+message,true);$('picker').hidden=false;window.currentData=null};

function normalizePreset(value,name){
 const p=value.volumeProperties?.[0],c=p?.components?.[0];let r;
 if(c){r={name,interpolationType:p.interpolationType==='nearest'?0:1,shade:!!c.shade,ambient:c.lighting?.ambient??.2,diffuse:c.lighting?.diffuse??.7,specular:c.lighting?.specular??.2,specularPower:c.lighting?.specularPower??10,scalarOpacityUnitDistance:c.scalarOpacityUnitDistance??1,disableGradientOpacity:!!c.disableGradientOpacity,colorSpace:0,color:c.rgbTransferFunction?.points?.map(q=>[q.x,...q.color,q.midpoint??.5,q.sharpness??0]),scalarOpacity:c.scalarOpacity?.points?.map(q=>[q.x,q.y,q.midpoint??.5,q.sharpness??0]),gradientOpacity:c.gradientOpacity?.points?.map(q=>[q.x,q.y,q.midpoint??.5,q.sharpness??0])}}else r={...value,name:value.name||name};
 for(const[key,n]of [['color',6],['scalarOpacity',4],['gradientOpacity',4]]){if(!Array.isArray(r[key])||!r[key].length||r[key].some(q=>q.length!==n||q.some(v=>!Number.isFinite(v))))throw Error(name+' 的 '+key+' 控制点无效');r[key].sort((a,b)=>a[0]-b[0]);if(r[key].some((q,i)=>i&&q[0]<=r[key][i-1][0]))throw Error(name+' 控制点位置重复');if(r[key].some(q=>q.at(-2)!==.5||q.at(-1)!==0))throw Error(name+' 使用暂不支持的非线性控制点')}
 if(r.colorSpace!==0)throw Error(name+' 使用暂不支持的非 RGB 颜色空间');for(const key of ['ambient','diffuse','specular','specularPower','scalarOpacityUnitDistance'])if(!Number.isFinite(r[key]))throw Error(name+' 的光照或距离参数无效');if(r.scalarOpacityUnitDistance<=0)throw Error(name+' 的采样单位距离无效');return r;
}
window.importedPresets=[];
document.getElementById('presets').onchange=async e=>{const map=new Map(),errors=[];const files=Array.from(e.target.files).filter(f=>/\.json$/i.test(f.name)).sort((a,b)=>Number(/\.vp\.json$/i.test(a.name))-Number(/\.vp\.json$/i.test(b.name)));
for(const f of files){try{const data=JSON.parse(await f.text());if(data.presets){for(const p of data.presets){const r=normalizePreset(p,p.name);map.set(r.name,r)}}else if(data.volumeProperties){const r=normalizePreset(data,f.name.replace(/\.vp\.json$/i,''));map.set(r.name,r)}else errors.push(f.name+'：不是体属性 JSON')}catch(err){errors.push(f.name+'：'+err.message)}}
window.importedPresets=[...map.values()].sort((a,b)=>a.name.localeCompare(b.name));document.getElementById('presetInfo').textContent=`已读取 ${map.size} 个预设${errors.length?'；跳过 '+errors.length+' 个文件':''}`;document.getElementById('presetErrors').textContent=errors.join('\n');document.getElementById('presetErrors').hidden=!errors.length;ready();
};
</script></body></html>